nvidia-video-G06.spec
Add GBM allocator symlink also for 32 bit, fixes gamescope/Steam coredump.
These are 32 bit applications.
https://github.com/ValveSoftware/steam-for-linux/issues/10916#issuecomment-2129975306
=> Fix gamescope/steam coredump

nvidia-driver-G06.spec
Not sure exactly what you are trying to accomplish here:
```
if [ "$ARCH" = "i386" -o "$ARCH" = "x86_64" ]; then
if [ -d "$SOURCES/arch/x86" ]; then
KERNEL_ARCH="x86"
fi
fi
```
In your idea this should make the test x86 test run on all architectures?
=> Remove useless replacement in conftest.sh

nvidia-video-G06.spec
And it was also limited in scope in terms of features/files bundled in the runfile.
=> ppc64le is no longer supported

nvidia-video-G06.spec
ICD loader files are not supposed to be modified by the user, they are just static configuration for loading the appropriate driver.
- Do not mark user modifiable configuration files under `%{_datadir}`, this folder should be read only.
- Do not put ICDs under `/etc/`, put them in `%{_datadir}`.
- Separate between 32/64 bit on `x86_64` as most packages do.
=> Standardize Vulkan/EGL ICDs installation

nvidia-video-G06.spec
There are no VDPAU libraries being shipped by this `nvidia-video-G06` as subpackages, they are built from source, this is probably a leftover.
Also, add the 32 bit VDPAU support to `nvidia-video-G06-32bit`.
=> Fix VDPAU 32 bit requirements and clean leftovers

nvidia-video-G06.spec
It's supported also on `aarch64`. Please note that this is not power management, and has nothing to do with compute utilities.
More of this later in another pull request.
=> Enable powerd on aarch64

nvidia-driver-G06.spec, nvidia-video-G06.spec
The generic `libOpenCL.so.1` library is just fine, this is shipped in the driver run file only if the target system does not have it.
=> Drop bundled libOpenCL and alternatives

nvidia-video-G06.spec
This fixes build related to changes ("Add changes for driver 560") for
* libnvidia-egl-gbm
* libnvidia-egl-wayland
* libnvidia-egl-xcb
* libnvidia-egl-xlib
=> fixed build for latest libnvidia-egl-* changes

nvidia-video-G06.spec
This merge requests reorgnizes components based on "topic", so CUDA/compute only, desktop related or both.
This same list of libraries/components for splits is in the current shipped drivers for Red Hat platforms. The logic in those distributions is roughly as follows:
- `nvidia-driver`, which contains all the desktop-only related files.
- `nvidia-driver-cuda`, which contains all the compute-only related files.
- `nvidia-kmod-common`, which is the common package between both and the kernel modules, required by the two above, and contains basically stuff in common.
Supporting libraries as in:
- `nvidia-driver-libs` and `nvidia-driver-libs.i686` for desktop and 32 bit desktop compatibility.
- `nvidia-driver-cuda-libs` and `nvidia-driver-cuda-libs.i686` for compute and 32 bit compute …
=> Reorganize components

nvidia-video-G06.spec
- Sort `systemd` units in alphabetical order (there's a new one coming).
- Do not glob `libnvidia-vksc-core.so.*` like the other libraries.
- Drop `%post` and `%postun` for `nvidia-compute-utils-G06`, `systemd` units are in `nvidia-video-G06` now.
- Do not touch `nvidia_drv.so` in `%post` and also don't check for it in a non existant path (?).
=> Small cleanup

50-nvidia.conf.modprobe, 70-nvidia-compute-G06.preset, 70-nvidia-video-G06.preset, nvidia-video-G06.spec
Drop the commands/scriptlets to add the `systemd` units for power management and instead ship presets for enabling all the required `systemd` units.
`70-nvidia-video-G06.preset` contained in `nvidia-video-G06` starts all the power management related `systemd` units.
`70-nvidia-compute-G06.preset` contained in `nvidia-compute-G06` starts the `nvidia-persistenced` daemon by default if installed (it always is).
Fix the documentation path (I used the Red Hat path in the previous MR) and move the HTML documentation to `nvidia-common-G06`, since it's related to both desktop and compute cases and `nvidia-common-G06` is always installed.
=> Add systemd preset, adjust documentation

nvidia-driver-G06.spec, nvidia-video-G06.spec
- Drop `nvidia_build`, I've finally convinced product management to not support anything that is already EOL by the vendors, so we also build on SLE 15sp5 / Leap 15.5.
- Move the creation of the folders at the top of the `%install` section closer to the various topics, this drops also creation of the `/usr/lib` folders on `aarch64`.
- Drop creation of unused `/usr/share/application/pixmaps` (leftover from the removal of `nvidia-settings`).
- `nvidia-common-G06` is actually a `noarch` package.
=> Make SPEC file a bit more readable

nvidia-video-G06.spec, preamble
Replacement for https://github.com/openSUSE/nvidia-driver-G06/pull/35 which for whatever reason it can not be re-opened.
=> Drop separate kernel package for firmware

50-nvidia.conf.modprobe
- Do not force D3 sleep state (power down) on pre-Ampere GPUs
- Allow saving the GPU memory to /var/tmp
=> Update power management configuration

60-nvidia.rules
Run the `udev` rule that calls `nvidia-modprobe` only when loading a kernel module.
This prevents an issue with compute nodes without modesetting enabled (so the modules can be unloaded) that prevents users from unloading the modules to make changes (NVSwitch, NVReg changes., filtering out GPUs, etc.). In case of a module unload, the module would get immediately reloaded because of the rule.
This prevents the rule from running at every single change, for example during an unload.
=> Run udev rule only on add/bind

kmp-postun.sh
When switching module implementation (open/proprietary), the modules installed by the second implementation are wiped out when the `%postun` section of the former implementation runs.
Example:
```
zypper install nvidia-open-driver-G06-kmp
zypper install --force nvidia-driver-G06-kmp
```
After the successful installation of `nvidia-driver-G06-kmp`, `nvidia-open-driver-G06-kmp` gets removed and *then* the `%postun` runs as the package is no longer installed, wiping out the modules installed by `nvidia-driver-G06-kmp`.
Unfortunately, we need to query the open driver in the proprietary one and viceversa, as at the time of the `%postun` run the package still appear. We can't also use a wildcard (ex. `rpm -q --quiet nvidia-driver-G06-kmp\*` to catch all KMP variants) as `rpm -q` would return 0 …
=> Fix issue when switching module implementation

nvidia-video-G06.spec
We removed openssl-1_1 from Tumbleweed. There is also libnvidia-pkcs11-openssl3.so available.
=> get rid of libnvidia-pkcs11.so, which still required openssl-1_1

nvidia-driver-G06.spec
Looks like a regression of RPM update to version 4.20. Related bugreport:
https://bugzilla.suse.com/show_bug.cgi?id=1236746
=> fixed build for TW by defining %_builddir and %_sourcedir if needed

50-nvidia.conf.modprobe
Added also nvidia-drm since on some machines it didn't get loaded automatically, which resulted in Wayland sessions falling back to simpledrm (slow!), external monitors and switcherooctl not working at all.
=> modprobe.d snippet: softdep (post) load also nvidia-drm (gh issue#86)

nvidia-video-G06.spec
This is to avoid dependancies to almost the whole desktop when just installing minimalistic nvidia-compute-G06 pkg. (gh#88)
=> moved 32bit libnvcuvid from video to compute package

kmp-filelist, nvidia-driver-G06.spec, nvidia-video-G06.spec
This is to prevent customers using the nvidia-installer when only the KMP has been installed. This can easily happen when the open driver KMP has been installed automatically without any other driver RPMs. So I decided to also add such a file to the open driver KMP. To prevent file conflicts between nvdia-common-G06 and the open driver KMP I moved this file now also to the proprietary KMP. The KMPs for prroprietary and open driver conflict anyway.
=> moved alternate-install-present from nvidia-common-G06 to KMP

kmp-trigger.sh, nvidia-video-G06.spec
Use '=' instead of '==' for comparing strings.
=> improve Bourne shell compatibility in scripts

nvidia-video-G06.spec
Initially this has been added for Steam application, but meanwhile the SUSE package for Steam triggers the installation of -32bit driver packages itself. So this is no longer needed.
=> Removed Recommends for -32bit driver packages

nvidia-video-G06.spec
Drop these Recommends:
```
Recommends:     Mesa-libGL1
Recommends:     Mesa-libEGL1
Recommends:     Mesa-libGLESv1_CM1
Recommends:     Mesa-libGLESv2-2
```
They are useless, and they are there because from what I see in the logs, in ~2018 the `libglvnd` equivalent provided by the run file where not deleted but included in the package unfiltered. So in case of installation, the NVIDIA driver package was providing the Mesa libraries.
=> Drop obsolete requirements

60-nvidia.conf.dracut
Avoid dracut error message about non-existing 'nvidia_peermem' when users add drivers to initrd.
For more details see https://bugzilla.suse.com/show_bug.cgi?id=1241114#c5
=> dracut config: removed not longer used 'nvidia_peermem' module (boo#1241114)

nvidia-video-G06.spec
- Add `libnvidia-present`, a Vullkan library that provides an extension for frame generation ([Smooth Motion](https://download.nvidia.com/XFree86/Linux-x86_64/575.51.02/README/nvpresent.html)). It adds a Vulkan layer extension and it's loaded through an extra stanza in `nvidia_layers.json`. Only for `x86_64`.
- Split out `libnvidia-gpucomp` in its own package, as it's required by destkop libraries now (`libnvidia-present`). Once the 32 bit fades away, the common library can go to `nvidia-common-G06`.
- `libnvidia-sandboxutils` is now also for `aarch64`.
Extra:
- Drop a leftover `update-alternatives` requirement.
- Match driver 575 with CUDA 12.9.
=> Changes for 575
